#let crosswalk-matrix = (
  (namespace: "metadata", pmbok: "Tailoring", prince2: "Organising", iso: "ISO 9001, ISO 27001"),
  (namespace: "initiation", pmbok: "Planning", prince2: "Business Case", iso: "ISO 21500"),
  (namespace: "baselines", pmbok: "Planning", prince2: "Plans", iso: "ISO 21500"),
  (namespace: "registers", pmbok: "Delivery", prince2: "Risk, Issues", iso: "ISO 31000"),
  (namespace: "governance", pmbok: "Measurement", prince2: "Progress", iso: "ISO 9001"),
  (namespace: "closure", pmbok: "Close Project", prince2: "End Project Report", iso: "ISO 9001")
)

#let glossary-terms = (
  (term: "Acceptance Criteria", definition: "Defined standards that a deliverable must meet to be accepted by the client.", aka: "Exit Criteria"),
  (term: "Assumption", definition: "A factor considered to be true for the sake of planning without empirical proof.", aka: "Hypothesis"),
  (term: "Baseline", definition: "The approved version of a scope, schedule, or budget used as a reference for performance measurement.", aka: "Target"),
  (term: "Business Case", definition: "The financial and strategic justification for undertaking a project.", aka: "Project Justification"),
  (term: "Change Request", definition: "A formal proposal to modify any document, deliverable, or baseline.", aka: "RFC"),
  (term: "Charter", definition: "A formal document that authorizes the existence of a project and provides the project manager with authority.", aka: "Project Brief"),
  (term: "Constraint", definition: "A limiting factor that affects the execution of a project.", aka: "Restriction"),
  (term: "Critical Path", definition: "The sequence of activities representing the longest path through a project, determining the shortest duration.", aka: "CPM"),
  (term: "Deliverable", definition: "Any unique and verifiable product, result, or capability required to be produced to complete a phase.", aka: "Output"),
  (term: "Exception", definition: "A situation where a project deviates significantly from its tolerances.", aka: "Deviation"),
  (term: "Issue Log", definition: "A project document where all realized blocks or challenges are recorded and tracked.", aka: "Blocker List"),
  (term: "Lessons Learned", definition: "Knowledge gained during a project which highlights successes and failures to improve future performance.", aka: "Retrospective"),
  (term: "Milestone", definition: "A significant point or event in a project schedule.", aka: "Checkpoint"),
  (term: "Product Breakdown Structure", definition: "A hierarchical structure of things that the project will make or outcomes that it will deliver.", aka: "PBS"),
  (term: "Quality Gate", definition: "A formal review point where deliverables are evaluated against quality standards.", aka: "Review Point"),
  (term: "RACI", definition: "A matrix mapping the project roles to responsibilities across tasks.", aka: "Responsibility Matrix"),
  (term: "RAG", definition: "A traffic light system to quickly classify the health of a project or task.", aka: "Red-Amber-Green"),
  (term: "Risk Register", definition: "A document detailing identified risks, their probability, impact, and mitigation strategies.", aka: "Risk Log"),
  (term: "Scope Creep", definition: "The uncontrolled expansion to product or project scope without adjustments to time, cost, and resources.", aka: "Feature Creep"),
  (term: "Sponsor", definition: "A person or group providing resources and support for the project, accountable for enabling success.", aka: "Executive Sponsor"),
  (term: "Stage Gate", definition: "A phase-end review used to evaluate project progress and determine if the project should continue.", aka: "Phase Gate"),
  (term: "Stakeholder", definition: "An individual, group, or organization that may affect or be affected by a decision or activity of the project.", aka: "Interested Party"),
  (term: "Tolerance", definition: "The permissible deviation from a baseline plan without escalating to a higher authority.", aka: "Variance Limit"),
  (term: "WBS", definition: "A hierarchical decomposition of the total scope of work to be carried out by the project team.", aka: "Work Breakdown Structure"),
  (term: "Work Package", definition: "The work defined at the lowest level of the work breakdown structure for which cost and duration are estimated and managed.", aka: "Task Group")
)

#let schema-rows = (
  (path: "metadata.id", type: "str", required: true, default: "\"\"", description: "Unique project identifier."),
  (path: "metadata.name", type: "str", required: true, default: "\"\"", description: "Human-readable project title."),
  (path: "metadata.version", type: "str", required: false, default: "\"0.0.0\"", description: "Document version."),
  (path: "metadata.status", type: "str", required: false, default: "\"\"", description: "Current general state."),
  (path: "metadata.locale", type: "str", required: false, default: "\"es-MX\"", description: "Language settings."),
  (path: "metadata.currency", type: "str", required: false, default: "\"MXN\"", description: "Currency display format."),
  (path: "metadata.created_at", type: "str", required: false, default: "\"\"", description: "Creation date."),
  (path: "metadata.updated_at", type: "str", required: false, default: "\"\"", description: "Last modification date."),
  (path: "metadata.confidentiality", type: "str", required: false, default: "\"Interno\"", description: "Security and confidentiality classification."),
  (path: "metadata.schema_version", type: "str", required: false, default: "\"0.0.1\"", description: "Schema tracking version."),
  (path: "metadata.client_name", type: "str", required: false, default: "\"\"", description: "Entity requesting the project."),
  (path: "metadata.client_logo", type: "any", required: false, default: "none", description: "Image asset for client."),
  (path: "metadata.doc_control", type: "dict", required: false, default: "(:)", description: "Revisions and distribution configuration."),
  (path: "metadata.glossary", type: "array", required: false, default: "()", description: "Project specific terms."),
  (path: "metadata.references", type: "array", required: false, default: "()", description: "Links or linked resources."),
  
  (path: "initiation.pitch", type: "dict", required: false, default: "(:)", description: "The overarching context and setup."),
  (path: "initiation.pitch.problem", type: "str", required: true, default: "\"\"", description: "Identified pain point."),
  (path: "initiation.pitch.solution", type: "str", required: true, default: "\"\"", description: "Proposed means to solve the problem."),
  (path: "initiation.objectives", type: "array", required: true, default: "()", description: "Measurable goals."),
  (path: "initiation.business_case", type: "dict", required: false, default: "(:)", description: "The strategic alignment element."),
  (path: "initiation.business_case.benefits", type: "array", required: true, default: "()", description: "Quantifiable benefits expected."),
  (path: "initiation.feasibility", type: "dict", required: false, default: "(:)", description: "Multi-dimensional evaluation."),
  (path: "initiation.recommendation", type: "dict", required: false, default: "(:)", description: "Approval justification statement."),
  
  (path: "baselines.scope", type: "dict", required: false, default: "(:)", description: "Deliverables layout."),
  (path: "baselines.schedule", type: "dict", required: false, default: "(:)", description: "Timeline definitions."),
  (path: "baselines.schedule.milestones", type: "array", required: false, default: "()", description: "Key dates."),
  (path: "baselines.financials", type: "dict", required: false, default: "(:)", description: "Monetary tracking."),
  (path: "baselines.financials.budget_items", type: "array", required: false, default: "()", description: "Allocations."),
  (path: "baselines.quality", type: "dict", required: false, default: "(:)", description: "Standards and QA definition."),
  (path: "baselines.legal", type: "dict", required: false, default: "(:)", description: "Contracts and IP considerations."),
  (path: "baselines.security", type: "dict", required: false, default: "(:)", description: "Cybersecurity boundaries."),
  
  (path: "registers.assumptions_log", type: "array", required: false, default: "()", description: "Working hypotheses."),
  (path: "registers.risk_register", type: "array", required: false, default: "()", description: "Identified threats and mitigations."),
  (path: "registers.risk_response", type: "array", required: false, default: "()", description: "Contingency deployments."),
  (path: "registers.issue_log", type: "array", required: false, default: "()", description: "Realized obstacles."),
  (path: "registers.change_log", type: "array", required: false, default: "()", description: "Modifications to baseline."),
  
  (path: "governance.team", type: "array", required: true, default: "()", description: "Core members."),
  (path: "governance.stakeholders", type: "array", required: false, default: "()", description: "External vested parties."),
  (path: "governance.raci_matrix", type: "array", required: false, default: "()", description: "Responsibility allocations."),
  (path: "governance.communications", type: "array", required: false, default: "()", description: "Cadence of status reports."),
  (path: "governance.meeting_cadence", type: "array", required: false, default: "()", description: "Sync schedules."),
  (path: "governance.current_status", type: "dict", required: false, default: "(:)", description: "Status iteration variables."),
  (path: "governance.status.rag_status", type: "str", required: true, default: "\"\"", description: "Overall RAG health."),
  (path: "governance.status.executive_summary", type: "str", required: false, default: "\"\"", description: "Leadership narrative."),
  
  (path: "closure.acceptance_date", type: "str", required: false, default: "\"\"", description: "Formal sign-off mark."),
  (path: "closure.handover", type: "dict", required: false, default: "(:)", description: "Transferred artifacts."),
  (path: "closure.lessons_learned", type: "array", required: false, default: "()", description: "Post-mortem observations."),
  (path: "closure.warranty", type: "dict", required: false, default: "(:)", description: "Post-launch guarantees."),
  (path: "closure.sign_off_matrix", type: "array", required: false, default: "()", description: "Approver checkpoints."),
  (path: "closure.signatures", type: "dict", required: false, default: "(:)", description: "Executors signature records.")
)
